// port-lint: source export.rs
package io.github.kotlinmania.tsrs.export

import io.github.kotlinmania.tsrs.Ts

public const val NOTE: String =
    "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n"

private const val HEADER_ERROR_MESSAGE =
    "The generated strings must have their NOTE and imports separated from their type declarations by a new line"

private const val DECLARATION_START = "export type "

private val exportPaths: MutableMap<String, MutableSet<String>> = mutableMapOf()

public fun getExportPaths(): Map<String, Set<String>> = exportPaths

public fun defaultOutDir(envDir: String? = null): String =
    envDir ?: "./bindings"

/**
 * Validates and returns the configured TypeScript import file extension.
 */
public fun importExtension(envValue: String? = null): Result<String> =
    when (envValue) {
        null, "" -> Result.success("")
        "js" -> Result.success(".js")
        "ts" -> Result.success(".ts")
        else -> Result.failure(ExportError.InvalidImportExtension)
    }

/**
 * Returns the required import path for importing [importPath] from the file [from].
 */
public fun importPath(
    from: String,
    importPath: String,
    importExtension: String = "",
    currentDirectory: String = ".",
): Result<String> {
    val normalizedFrom = from.replace('\\', '/')
    val fromParent =
        if (normalizedFrom.contains('/')) {
            normalizedFrom.substringBeforeLast('/')
        } else {
            "."
        }

    val diffResult = diffPaths(importPath, fromParent, currentDirectory)
    val relPath = diffResult.getOrElse { return Result.failure(it) }

    val strPath =
        if (!relPath.startsWith(".") && !relPath.startsWith("/")) {
            "./$relPath"
        } else {
            relPath
        }

    val cleanPath = strPath.removeSuffix(".ts")
    return Result.success("$cleanPath$importExtension")
}

/**
 * Generates the TypeScript declaration for [type].
 */
public fun generateDecl(type: Ts): String {
    val builder = StringBuilder()
    type.docs()?.let { builder.append(it) }
    builder.append("export ")
    builder.append(type.decl())
    return builder.toString()
}

/**
 * Generates the import statements for dependencies of [type].
 */
public fun generateImports(
    type: Ts,
    outDir: String = defaultOutDir(),
    importExtension: String = "",
): Result<String> {
    val path =
        type.outputPath()?.let { "$outDir/$it" } ?: return Result.failure(
            ExportError.CannotBeExported(type.name()),
        )
    val deps = type.dependencies()
    val deduplicated =
        deps
            .filter { it.typeId != type.ident() }
            .associateBy { it.tsName }

    val imports = mutableMapOf<String, MutableSet<String>>()

    for ((_, dep) in deduplicated) {
        val depPath = "$outDir/${dep.outputPath}"
        val relPath = importPath(path, depPath, importExtension).getOrElse { return Result.failure(it) }
        val normalizedPath = path.substringAfterLast('/').removeSuffix(".ts")
        val isSameFile = "./$normalizedPath" == relPath.removeSuffix(".js")
        if (isSameFile) continue
        val set = imports.getOrPut(relPath) { mutableSetOf() }
        set.add(dep.tsName)
    }

    val out = StringBuilder()
    for (p in imports.keys.sorted()) {
        val types = imports.getValue(p).sorted()
        out.append("import type { ")
        out.append(types.joinToString(", "))
        out.append(" } from \"")
        out.append(p)
        out.append("\";\n")
    }
    if (imports.isNotEmpty()) {
        out.append("\n")
    }
    return Result.success(out.toString())
}

/**
 * Returns the generated definition for [type].
 */
public fun exportToString(
    type: Ts,
    outDir: String = defaultOutDir(),
    importExtension: String = "",
): Result<String> {
    val buffer = StringBuilder()
    buffer.append(NOTE)
    val imp = generateImports(type, outDir, importExtension).getOrElse { return Result.failure(it) }
    buffer.append(imp)
    buffer.append(generateDecl(type))
    buffer.append("\n")
    return Result.success(buffer.toString())
}

/**
 * Export [type] to the file specified by [path].
 */
public fun exportTo(type: Ts, path: String): Result<Unit> =
    exportAndMerge(path, type.ident(), exportToString(type).getOrElse { return Result.failure(it) })

/**
 * Export [type] into the given directory [outDir].
 */
public fun exportInto(type: Ts, outDir: String): Result<Unit> {
    val path = type.outputPath() ?: return Result.failure(ExportError.CannotBeExported(type.name()))
    val joined = "$outDir/$path"
    val absPath = absolute(joined).getOrElse { return Result.failure(it) }
    return exportTo(type, absPath)
}

/**
 * Exports [type] and all dependencies into [outDir].
 */
public fun exportAllInto(type: Ts, outDir: String): Result<Unit> {
    val seen = mutableSetOf<String>()
    return exportRecursive(type, seen, outDir)
}

private fun exportRecursive(type: Ts, seen: MutableSet<String>, outDir: String): Result<Unit> {
    if (!seen.add(type.ident())) return Result.success(Unit)
    exportInto(type, outDir).getOrElse { return Result.failure(it) }
    var errorResult: Result<Unit>? = null
    type.visitDependencies { dep ->
        if (errorResult == null && dep.outputPath() != null) {
            val res = exportRecursive(dep, seen, outDir)
            if (res.isFailure) {
                errorResult = res
            }
        }
    }
    return errorResult ?: Result.success(Unit)
}

/**
 * Merges and saves or registers export in export paths.
 */
public fun exportAndMerge(path: String, typeName: String, generatedType: String): Result<Unit> {
    val entry = exportPaths.getOrPut(path) { mutableSetOf() }
    if (entry.contains(typeName)) return Result.success(Unit)
    entry.add(typeName)
    return Result.success(Unit)
}

/**
 * Inserts the imports and declaration from the newly generated type into the contents
 * of the file, removing duplicate imports and organizing both imports and declarations alphabetically.
 */
public fun merge(originalContents: String, newContents: String): String {
    val originalParts = originalContents.split("\n\n", limit = 2)
    require(originalParts.size == 2) { HEADER_ERROR_MESSAGE }
    val originalHeader = originalParts[0]
    val originalDecls = originalParts[1]

    val newParts = newContents.split("\n\n", limit = 2)
    require(newParts.size == 2) { HEADER_ERROR_MESSAGE }
    val newHeader = newParts[0]
    val newDecl = newParts[1]

    val originalImportLines = originalHeader.lines().drop(1)
    val newImportLines = newHeader.lines().drop(1)

    val importsMap = mutableMapOf<String, MutableSet<String>>()

    for (line in originalImportLines + newImportLines) {
        if (line.isBlank() || !line.contains(" from ")) continue
        val parts = line.split(" from ", limit = 2)
        val importPart = parts[0]
        val fromPart = parts[1]
        val path = fromPart.trim().trimStart('"').trimEnd('"', ';')

        val types =
            importPart
                .trim()
                .removePrefix("import type { ")
                .removeSuffix(" }")
                .split(", ")
                .map { it.trim() }
                .filter { it.isNotEmpty() }

        val set = importsMap.getOrPut(path) { mutableSetOf() }
        set.addAll(types)
    }

    val importsBuilder = StringBuilder()
    for (path in importsMap.keys.sorted()) {
        val types = importsMap.getValue(path).sorted()
        importsBuilder.append("import type { ")
        importsBuilder.append(types.joinToString(", "))
        importsBuilder.append(" } from \"")
        importsBuilder.append(path)
        importsBuilder.append("\";\n")
    }

    val imports = importsBuilder.toString()
    val buffer = StringBuilder()
    buffer.append(imports)

    val cleanNewDecl = newDecl.trim('\n')
    val newDeclName =
        cleanNewDecl
            .substringAfter(DECLARATION_START, "")
            .trimStart()
            .split(Regex("\\s+"))
            .firstOrNull() ?: ""

    val originalDeclList = originalDecls.split("\n\n").map { it.trim('\n') }.filter { it.isNotEmpty() }

    var inserted = false
    for (decl in originalDeclList) {
        val declName =
            decl
                .substringAfter(DECLARATION_START, "")
                .trimStart()
                .split(Regex("\\s+"))
                .firstOrNull() ?: ""

        if (inserted || declName < newDeclName) {
            buffer.append('\n')
            buffer.append(decl)
            buffer.append('\n')
        } else {
            buffer.append('\n')
            buffer.append(cleanNewDecl)
            buffer.append('\n')

            buffer.append('\n')
            buffer.append(decl)
            buffer.append('\n')

            inserted = true
        }
    }

    if (!inserted) {
        buffer.append('\n')
        buffer.append(cleanNewDecl)
        buffer.append('\n')
    }

    return buffer.toString()
}
