// port-lint: source src/export.rs
package io.github.kotlinmania.tsrs.export

public const val NOTE: String =
    "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.\n"

private const val HEADER_ERROR_MESSAGE =
    "The generated strings must have their NOTE and imports separated from their type declarations by a new line"

private const val DECLARATION_START = "export type "

/**
 * Validates and returns the configured TypeScript import file extension.
 */
public fun importExtension(envValue: String? = null): Result<String> =
    when (envValue) {
        null, "" -> Result.success("")
        "js" -> Result.success(".js")
        "ts" -> Result.success(".ts")
        else -> Result.failure(ExportError.InvalidImportExtension)
    }

/**
 * Returns the required import path for importing [importPath] from the file [from].
 */
public fun importPath(
    from: String,
    importPath: String,
    importExtension: String = "",
    currentDirectory: String = ".",
): Result<String> {
    val normalizedFrom = from.replace('\\', '/')
    val fromParent =
        if (normalizedFrom.contains('/')) {
            normalizedFrom.substringBeforeLast('/')
        } else {
            "."
        }

    val diffResult = diffPaths(importPath, fromParent, currentDirectory)
    val relPath = diffResult.getOrElse { return Result.failure(it) }

    val strPath =
        if (!relPath.startsWith(".") && !relPath.startsWith("/")) {
            "./$relPath"
        } else {
            relPath
        }

    val cleanPath = strPath.removeSuffix(".ts")
    return Result.success("$cleanPath$importExtension")
}

/**
 * Inserts the imports and declaration from the newly generated type into the contents
 * of the file, removing duplicate imports and organizing both imports and declarations alphabetically.
 */
public fun merge(originalContents: String, newContents: String): String {
    val originalParts = originalContents.split("\n\n", limit = 2)
    require(originalParts.size == 2) { HEADER_ERROR_MESSAGE }
    val originalHeader = originalParts[0]
    val originalDecls = originalParts[1]

    val newParts = newContents.split("\n\n", limit = 2)
    require(newParts.size == 2) { HEADER_ERROR_MESSAGE }
    val newHeader = newParts[0]
    val newDecl = newParts[1]

    val originalImportLines = originalHeader.lines().drop(1)
    val newImportLines = newHeader.lines().drop(1)

    val importsMap = mutableMapOf<String, MutableSet<String>>()

    for (line in originalImportLines + newImportLines) {
        if (line.isBlank() || !line.contains(" from ")) continue
        val parts = line.split(" from ", limit = 2)
        val importPart = parts[0]
        val fromPart = parts[1]
        val path = fromPart.trim().trimStart('"').trimEnd('"', ';')

        val types =
            importPart
                .trim()
                .removePrefix("import type { ")
                .removeSuffix(" }")
                .split(", ")
                .map { it.trim() }
                .filter { it.isNotEmpty() }

        val set = importsMap.getOrPut(path) { mutableSetOf() }
        set.addAll(types)
    }

    val importsBuilder = StringBuilder()
    for (path in importsMap.keys.sorted()) {
        val types = importsMap.getValue(path).sorted()
        importsBuilder.append("import type { ")
        importsBuilder.append(types.joinToString(", "))
        importsBuilder.append(" } from \"")
        importsBuilder.append(path)
        importsBuilder.append("\";\n")
    }

    val imports = importsBuilder.toString()
    val buffer = StringBuilder()
    buffer.append(imports)

    val cleanNewDecl = newDecl.trim('\n')
    val newDeclName =
        cleanNewDecl
            .substringAfter(DECLARATION_START, "")
            .trimStart()
            .split(Regex("\\s+"))
            .firstOrNull() ?: ""

    val originalDeclList = originalDecls.split("\n\n").map { it.trim('\n') }.filter { it.isNotEmpty() }

    var inserted = false
    for (decl in originalDeclList) {
        val declName =
            decl
                .substringAfter(DECLARATION_START, "")
                .trimStart()
                .split(Regex("\\s+"))
                .firstOrNull() ?: ""

        if (inserted || declName < newDeclName) {
            buffer.append('\n')
            buffer.append(decl)
            buffer.append('\n')
        } else {
            buffer.append('\n')
            buffer.append(cleanNewDecl)
            buffer.append('\n')

            buffer.append('\n')
            buffer.append(decl)
            buffer.append('\n')

            inserted = true
        }
    }

    if (!inserted) {
        buffer.append('\n')
        buffer.append(cleanNewDecl)
        buffer.append('\n')
    }

    return buffer.toString()
}
